version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: protocolx-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: protocolx
    volumes:
      - ./scripts/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql
    networks:
      - protocolx-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: protocolx-redis
    ports:
      - "6379:6379"
    networks:
      - protocolx-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: user-auth-service
    image: protocolx/user-auth-service:latest
    container_name: protocolx-user-auth-service
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/protocolx_users
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - protocolx-network

  order-management-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: order-management-service
    image: protocolx/order-management-service:latest
    container_name: protocolx-order-management-service
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/protocolx_orders
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_REDIS_HOST=redis
      - MATCHING_ENGINE_HOST=matching-engine
    networks:
      - protocolx-network

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: api-gateway
    image: protocolx/api-gateway:latest
    container_name: protocolx-api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-auth-service
      - order-management-service
    environment:
      - USER_AUTH_SERVICE_URL=http://user-auth-service:8081
      - ORDER_MANAGEMENT_SERVICE_URL=http://order-management-service:8082
    networks:
      - protocolx-network

  matching-engine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: matching-engine
    image: protocolx/matching-engine:latest
    container_name: protocolx-matching-engine
    ports:
      - "9090:9090"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SPRING_REDIS_HOST=redis
    networks:
      - protocolx-network

networks:
  protocolx-network:
    driver: bridge