FROM eclipse-temurin:21-jdk-alpine AS build
WORKDIR /workspace/app

ARG MODULE

COPY . .

RUN chmod +x ./gradlew && \
    ./gradlew ${MODULE}:dependencies --no-daemon && \
    ./gradlew ${MODULE}:build -x test --no-daemon

FROM eclipse-temurin:21-jre-alpine
VOLUME /tmp

ARG MODULE
COPY --from=build /workspace/app/${MODULE}/build/libs/*.jar app.jar

# non-root user
RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup && \
    chown -R appuser:appgroup /app.jar
USER appuser

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]